
services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./logs:/app/logs
      - ./temp_downloads:/app/temp_downloads
    restart: unless-stopped
    environment:
      - STAGE=${STAGE:-production}
      - VALID_TOKEN=${VALID_TOKEN:-sample}
      - AUTO_DELETE_LOGS=${AUTO_DELETE_LOGS:-True}
      - HEADLESS_MODE=${HEADLESS_MODE:-auto}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR:-temp_downloads}
      - PAGE_MAX_TIMEOUT=${PAGE_MAX_TIMEOUT:-7}
      - DOWNLOAD_MAX_TIMEOUT=${DOWNLOAD_MAX_TIMEOUT:-4}
      - BASE_URL=${BASE_URL:-https://www.google.com/}
