name: 🧪 CI Test Suite

on:
  workflow_call:
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Copiar .env.example como .env
        run: cp .env.example .env

      - name: Start Docker Compose in detached mode
        run: |
          docker-compose up --build -d

      - name: Run pytest
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest --maxfail=1 --disable-warnings -v

      - name: Stop Docker Compose
        run: |
          docker-compose down
