name: 🔎 Code Review

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Code Review GPT
        uses: mattzcarey/shippie@v0.18.0